services:
  rads-explorer:
    image: ra-ds-explorer:latest
    container_name: explorer

    build:
      context: .
      dockerfile: docker/Dockerfile

    ports:
      - "9000:9000"

    env_file:
      - .env

    environment:
      RADP_CURL_PATH: ${RADP_CURL_PATH}
      RADP_CERT_THUMBPRINT: ${RADP_CERT_THUMBPRINT}
      RADP_TRANSPORT: ${RADP_TRANSPORT}
      RADP_API_BASE_URL: ${RADP_API_BASE_URL}

    restart: always

    networks:
      - ra-network

networks:
  ra-network:
    external: true
